modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Mecha Soldier PLASTAR"
authors = "LemmaEOF, Khazoda, Snakefangox, MattiDragon, MerchantPug, Kneelawk"
description = "Tiny Mecha Mod@"
logoFile = "assets/${mod_id}/icon.png"

[[mixins]]
config = "plastar.mixins.json"

[[accessTransformers]]
file = "common-at.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "flywheel"
type = "REQUIRED"
versionRange = "[1.0.0-beta,2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "smartbrainlib"
type = "REQUIRED"
versionRange = "[1.8,)"
ordering = "NONE"
side = "BOTH"
